-- Seed data for PlantTypes table
-- Insertar tipos de plantas comunes para microgreens

INSERT INTO "PlantTypes" (
    "id",
    "name", 
    "scientificName",
    "category",
    "description",
    "daysToGerminate",
    "daysToHarvest",
    "optimalTemp",
    "optimalHumidity",
    "lightRequirement",
    "averageYield",
    "marketPrice",
    "difficulty",
    "createdAt",
    "updatedAt"
) VALUES 
-- Microgreens populares
(
    'cm0xj1k2l0000h8q7v5n4m3p2',
    'Microgreen de Rúcula',
    'Eruca sativa',
    'Microgreens',
    'Microgreens de sabor picante y aromático, muy populares en ensaladas gourmet',
    2,
    10,
    18.5,
    65.0,
    'Medium',
    120.0,
    0.15,
    'Easy',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cm0xj1k2l0001h8q7v5n4m3p3',
    'Microgreen de Brócoli',
    'Brassica oleracea',
    'Microgreens',
    'Microgreens nutritivos con alto contenido de vitaminas y sabor suave',
    3,
    12,
    20.0,
    70.0,
    'Medium',
    100.0,
    0.12,
    'Easy',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cm0xj1k2l0002h8q7v5n4m3p4',
    'Microgreen de Rábano',
    'Raphanus sativus',
    'Microgreens',
    'Microgreens con sabor picante intenso, excelente para decorar platos',
    2,
    8,
    18.0,
    60.0,
    'Medium',
    110.0,
    0.18,
    'Easy',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cm0xj1k2l0003h8q7v5n4m3p5',
    'Microgreen de Col Rizada',
    'Brassica oleracea var. acephala',
    'Microgreens',
    'Microgreens con sabor suave y textura crujiente, rico en nutrientes',
    3,
    14,
    19.0,
    65.0,
    'Medium',
    95.0,
    0.14,
    'Medium',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cm0xj1k2l0004h8q7v5n4m3p6',
    'Microgreen de Mostaza',
    'Brassica juncea',
    'Microgreens',
    'Microgreens de sabor intenso y picante, crecimiento rápido',
    2,
    9,
    20.0,
    65.0,
    'Medium',
    115.0,
    0.16,
    'Easy',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cm0xj1k2l0005h8q7v5n4m3p7',
    'Microgreen de Guisante',
    'Pisum sativum',
    'Microgreens',
    'Microgreens dulces con textura tierna, muy apreciados por chefs',
    4,
    16,
    16.0,
    75.0,
    'Low',
    140.0,
    0.20,
    'Medium',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cm0xj1k2l0006h8q7v5n4m3p8',
    'Microgreen de Girasol',
    'Helianthus annuus',
    'Microgreens',
    'Microgreens con sabor a nuez, textura crujiente y muy nutritivos',
    3,
    12,
    21.0,
    60.0,
    'High',
    160.0,
    0.25,
    'Medium',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- Hierbas aromáticas
(
    'cm0xj1k2l0007h8q7v5n4m3p9',
    'Albahaca',
    'Ocimum basilicum',
    'Herbs',
    'Hierba aromática clásica, ideal para cocina italiana y asiática',
    5,
    21,
    24.0,
    70.0,
    'High',
    80.0,
    0.30,
    'Medium',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cm0xj1k2l0008h8q7v5n4m3pa',
    'Cilantro',
    'Coriandrum sativum',
    'Herbs',
    'Hierba aromática muy usada en cocina mexicana y asiática',
    7,
    25,
    18.0,
    65.0,
    'Medium',
    75.0,
    0.25,
    'Easy',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cm0xj1k2l0009h8q7v5n4m3pb',
    'Perejil',
    'Petroselinum crispum',
    'Herbs',
    'Hierba aromática versátil, muy usada como guarnición y condimento',
    10,
    30,
    20.0,
    70.0,
    'Medium',
    70.0,
    0.20,
    'Easy',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- Vegetales de hoja verde
(
    'cm0xj1k2l000ah8q7v5n4m3pc',
    'Lechuga Mantecosa',
    'Lactuca sativa',
    'Leafy Greens',
    'Lechuga de textura suave y sabor delicado, ideal para ensaladas',
    3,
    35,
    16.0,
    80.0,
    'Medium',
    200.0,
    0.08,
    'Easy',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cm0xj1k2l000bh8q7v5n4m3pd',
    'Espinaca Baby',
    'Spinacia oleracea',
    'Leafy Greens',
    'Espinaca tierna rica en hierro y vitaminas, sabor suave',
    5,
    28,
    15.0,
    75.0,
    'Low',
    180.0,
    0.10,
    'Easy',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

-- Verificar inserción
SELECT COUNT(*) as "Total Plant Types Inserted" FROM "PlantTypes";